apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-petclinic-gateway-route
  namespace: default
spec:
  service:
    name: spring-petclinic-protected
    #!uri: https://spring-petclinic-protected-default.akslab4.tap.fynesy.com
  routes:
  - predicates:
      - Path=/**
    filters:
      - StripPrefix=0